### ISSUE TITLE
unnecessary assertion since it does not change the type of the expression.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/generator-react-sdk#154]
More info on this issue can be found [here](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=asyncapi_generator-react-sdk&open=AYNj_5YhhMC8RQbKx-mF)

**Comment by toukirkhan** [comment]
Assign me

**Comment by derberg** [comment]
@toukirkhan as I wrote in https://github.com/asyncapi/website/issues/998#issuecomment-1265264681 we do not assign issues here. You can easily block all the others from work this way. What matters is who opens up a PR first.

**Comment by toukirkhan** [comment]
ok

**Comment by derberg** [comment]
closing, current sonar cloud results show that all is good
