### ISSUE TITLE
LICENSE file is missing information

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator-react-sdk#20]
#### Describe the bug
LICENSE file does not contain correct information - https://github.com/asyncapi/generator-react-sdk/blob/0878a17a17838bb17734c64f2ce8fe505cfb66ed/LICENSE#L189

**Comment by jonaslagoni** [comment]
Seems like this is for all repositories in the organization.

**Comment by derberg** [comment]
@jonaslagoni why don't you set it the same as OAI https://github.com/OAI/OpenAPI-Specification/blob/main/LICENSE#L189 and do it in others whenever there is time. Even Kubernetes doesn't have it right, I guess it is not super critical, not at all I would say 😄 maybe this is another reason for the global workflows action to support also other files 🤷🏼

**Comment by magicmatatjahu** [comment]
Still valid. 

@derberg Should we fix it, or wait for this mentioned global workflow?

**Comment by derberg** [comment]
don't wait for it, just fix the file manually now if you want, not sure when global workflow will start supporting files other than the GH Actions
