### ISSUE TITLE
react warnings are loud when generating react templates

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator-react-sdk#37]
#### Describe the bug
When I generate markdown template I get this in the console

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Server (/Users/wookiee/sources/markdown-template/__transpiled/asyncapi.js:227:26)
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Text>. See https://reactjs.org/link/warning-keys for more information.
    at Schema (/Users/wookiee/sources/markdown-template/__transpiled/asyncapi.js:320:21)
```

#### How to Reproduce
just generate with markdown-template and you'll see it

#### Expected behavior
these logs should not be visible

**Comment by jonaslagoni** [comment]
If I am not mistaken this is currently not possible to solve natively since React does not allow us to suppress these warnings... 

Solutions:
- Use production build. Is that even possible with the npm package? - https://reactjs.org/docs/optimizing-performance.html#use-the-production-build
- Hook into console log and alter default behavior - https://stackoverflow.com/questions/57904356/how-to-hide-componentwillmount-warnings/60818832#60818832

cc @magicmatatjahu

**Comment by magicmatatjahu** [comment]
Production build also throw errors, but as error code :) Hooking default behaviour of console is not a good option. We should fix this error in template or write our own JSX pragma.

**Comment by jonaslagoni** [comment]
> Production build also throw errors, but as error code

Are you sure? Since the warnings shown by @derberg are only optimizations they would be removed by the production build right? 

As per https://reactjs.org/docs/optimizing-performance.html#use-the-production-build
> By default, React includes many helpful warnings. These warnings are very useful in development. However, they make React larger and slower so you should make sure to use the production version when you deploy the app.

**Comment by micaelmbagira** [comment]
@jonaslagoni why not fixing the warnings and adding the `"key"` prop to the children?

**Comment by jonaslagoni** [comment]
> @jonaslagoni why not fixing the warnings and adding the `"key"` prop to the children?

That will most likely also be needed, but the problem is all React templates have this problem. 

> Keys help React identify which items have changed, are added, or are removed
https://reactjs.org/link/warning-keys 

With our use case, this warning does not apply to us. So if we somehow could suppress them, that would solve all the problems.
